"""Shared PostgreSQL schema helpers for chat persistence adapters."""

from __future__ import annotations

from typing import Any


def init_postgres_workspaces_schema(cursor: Any) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS workspaces (
            workspace_id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT DEFAULT '',
            color TEXT DEFAULT 'blue',
            default_panels_json TEXT DEFAULT '[]',
            tool_config_json TEXT DEFAULT '{}',
            output_preset_json TEXT DEFAULT '{}',
            is_active INTEGER DEFAULT 0,
            created_at DOUBLE PRECISION NOT NULL,
            updated_at DOUBLE PRECISION NOT NULL
        )
        """
    )


def init_postgres_sessions_schema(cursor: Any) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS sessions (
            session_id TEXT PRIMARY KEY,
            created_at DOUBLE PRECISION NOT NULL,
            updated_at DOUBLE PRECISION NOT NULL,
            title TEXT DEFAULT '',
            is_archived INTEGER DEFAULT 0,
            is_favorite INTEGER DEFAULT 0,
            is_pinned INTEGER DEFAULT 0,
            session_order DOUBLE PRECISION DEFAULT 0,
            tags_json TEXT DEFAULT '[]',
            workspace_id TEXT DEFAULT 'workspace-default'
        )
        """
    )


def init_postgres_session_panels_schema(cursor: Any) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS session_panels (
            session_id TEXT NOT NULL,
            panel_id TEXT NOT NULL,
            provider TEXT DEFAULT 'ollama',
            connection_type TEXT DEFAULT '',
            model TEXT DEFAULT '',
            base_url TEXT DEFAULT '',
            api_key_ref TEXT DEFAULT '',
            temperature DOUBLE PRECISION DEFAULT 0.3,
            agent_mode TEXT DEFAULT 'auto',
            display_order INTEGER DEFAULT 0,
            is_primary INTEGER DEFAULT 0,
            created_at DOUBLE PRECISION NOT NULL,
            updated_at DOUBLE PRECISION NOT NULL,
            PRIMARY KEY (session_id, panel_id)
        )
        """
    )
    cursor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_session_panels_session
        ON session_panels(session_id, display_order)
        """
    )


def init_postgres_messages_schema(cursor: Any) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            type TEXT NOT NULL,
            content TEXT NOT NULL,
            timestamp DOUBLE PRECISION NOT NULL,
            model_id TEXT DEFAULT '',
            panel_id TEXT DEFAULT '',
            answer_group_id TEXT DEFAULT '',
            images_json TEXT DEFAULT '',
            files_json TEXT DEFAULT '',
            sources_json TEXT DEFAULT '',
            workflow_json TEXT DEFAULT '',
            token_usage_json TEXT DEFAULT '',
            task_id TEXT DEFAULT '',
            task_type TEXT DEFAULT '',
            feedback_value INTEGER DEFAULT 0
        )
        """
    )
    cursor.execute(
        "ALTER TABLE messages ADD COLUMN IF NOT EXISTS token_usage_json TEXT DEFAULT ''"
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS message_search (
            rowid BIGINT PRIMARY KEY,
            session_id TEXT NOT NULL,
            content TEXT NOT NULL
        )
        """
    )
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_session ON messages(session_id)")
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS idx_session_panel ON messages(session_id, panel_id)"
    )
    cursor.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_human_group
        ON messages(session_id, type, panel_id, answer_group_id)
        WHERE type = 'human' AND panel_id = '' AND answer_group_id <> ''
        """
    )
    cursor.execute(
        "CREATE INDEX IF NOT EXISTS idx_message_search_session ON message_search(session_id)"
    )


def init_postgres_core_chat_schema(cursor: Any) -> None:
    """Initialize the tables shared by session and message persistence."""

    init_postgres_workspaces_schema(cursor)
    init_postgres_sessions_schema(cursor)
    init_postgres_session_panels_schema(cursor)
    init_postgres_messages_schema(cursor)


def init_postgres_session_memory_schema(cursor: Any) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS session_memory (
            id TEXT PRIMARY KEY,
            session_id TEXT NOT NULL,
            kind TEXT NOT NULL,
            content TEXT NOT NULL,
            meta_json TEXT DEFAULT '{}',
            created_at DOUBLE PRECISION NOT NULL,
            updated_at DOUBLE PRECISION NOT NULL
        )
        """
    )
    cursor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_session_memory_session
        ON session_memory(session_id)
        """
    )
    cursor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_session_memory_session_updated
        ON session_memory(session_id, updated_at DESC)
        """
    )


def init_postgres_retrieval_feedback_schema(cursor: Any) -> None:
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS retrieval_feedback (
            id BIGSERIAL PRIMARY KEY,
            session_id TEXT NOT NULL,
            panel_id TEXT NOT NULL,
            answer_group_id TEXT NOT NULL,
            source_key TEXT NOT NULL,
            source_type TEXT DEFAULT '',
            source_title TEXT DEFAULT '',
            source_url TEXT DEFAULT '',
            feedback_value INTEGER NOT NULL DEFAULT 0,
            created_at DOUBLE PRECISION NOT NULL,
            updated_at DOUBLE PRECISION NOT NULL
        )
        """
    )
    cursor.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_retrieval_feedback_unique
        ON retrieval_feedback(session_id, panel_id, answer_group_id, source_key)
        """
    )
    cursor.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_retrieval_feedback_lookup
        ON retrieval_feedback(session_id, answer_group_id, panel_id, updated_at DESC)
        """
    )


__all__ = [
    "init_postgres_core_chat_schema",
    "init_postgres_messages_schema",
    "init_postgres_retrieval_feedback_schema",
    "init_postgres_session_memory_schema",
    "init_postgres_session_panels_schema",
    "init_postgres_sessions_schema",
    "init_postgres_workspaces_schema",
]
