"""PostgreSQL chat message history adapter."""

from __future__ import annotations

import json
import time
from typing import Any, Callable, Optional

from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage

from backend.chat_store import (
    DEFAULT_WORKSPACE_ID,
    _build_human_message_content_for_model,
    _build_search_preview,
    _derive_session_title,
    _env_int,
    _normalize_content,
    _normalize_files,
    _normalize_images,
    _normalize_message_feedback_value,
    _normalize_metadata_list,
    _parse_json_list,
)
from backend.stores.pg_base import PostgresStoreMixin


class PostgresChatMessageHistory(PostgresStoreMixin, BaseChatMessageHistory):
    """PostgreSQL-backed subset of ``SQLiteChatMessageHistory``.

    This intentionally mirrors the low-risk message runtime surface first:
    add/get/clear/search plus panel-specific reads. Higher-level session,
    workspace, bookmark, and feedback helpers still live in ``chat_store.py``.
    """

    def __init__(
        self,
        session_id: str,
        dsn: str | None = None,
        *,
        connection_factory: Callable[..., Any] | None = None,
    ) -> None:
        PostgresStoreMixin.__init__(self, dsn, connection_factory=connection_factory)
        self.session_id = str(session_id or "").strip()
        self.db_path = self.dsn
        self._init_db()
        self._ensure_session_exists()

    def _init_db(self) -> None:
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS workspaces (
                        workspace_id TEXT PRIMARY KEY,
                        name TEXT NOT NULL,
                        description TEXT DEFAULT '',
                        color TEXT DEFAULT 'blue',
                        default_panels_json TEXT DEFAULT '[]',
                        tool_config_json TEXT DEFAULT '{}',
                        output_preset_json TEXT DEFAULT '{}',
                        is_active INTEGER DEFAULT 0,
                        created_at DOUBLE PRECISION NOT NULL,
                        updated_at DOUBLE PRECISION NOT NULL
                    )
                    """
                )
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS sessions (
                        session_id TEXT PRIMARY KEY,
                        created_at DOUBLE PRECISION NOT NULL,
                        updated_at DOUBLE PRECISION NOT NULL,
                        title TEXT DEFAULT '',
                        is_archived INTEGER DEFAULT 0,
                        is_favorite INTEGER DEFAULT 0,
                        is_pinned INTEGER DEFAULT 0,
                        session_order DOUBLE PRECISION DEFAULT 0,
                        tags_json TEXT DEFAULT '[]',
                        workspace_id TEXT DEFAULT 'workspace-default'
                    )
                    """
                )
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS session_panels (
                        session_id TEXT NOT NULL,
                        panel_id TEXT NOT NULL,
                        provider TEXT DEFAULT 'ollama',
                        connection_type TEXT DEFAULT '',
                        model TEXT DEFAULT '',
                        base_url TEXT DEFAULT '',
                        api_key_ref TEXT DEFAULT '',
                        temperature DOUBLE PRECISION DEFAULT 0.3,
                        agent_mode TEXT DEFAULT 'auto',
                        display_order INTEGER DEFAULT 0,
                        is_primary INTEGER DEFAULT 0,
                        created_at DOUBLE PRECISION NOT NULL,
                        updated_at DOUBLE PRECISION NOT NULL,
                        PRIMARY KEY (session_id, panel_id)
                    )
                    """
                )
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS messages (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        session_id TEXT NOT NULL,
                        type TEXT NOT NULL,
                        content TEXT NOT NULL,
                        timestamp DOUBLE PRECISION NOT NULL,
                        model_id TEXT DEFAULT '',
                        panel_id TEXT DEFAULT '',
                        answer_group_id TEXT DEFAULT '',
                        images_json TEXT DEFAULT '',
                        files_json TEXT DEFAULT '',
                        sources_json TEXT DEFAULT '',
                        workflow_json TEXT DEFAULT '',
                        task_id TEXT DEFAULT '',
                        task_type TEXT DEFAULT '',
                        feedback_value INTEGER DEFAULT 0
                    )
                    """
                )
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS message_search (
                        rowid BIGINT PRIMARY KEY,
                        session_id TEXT NOT NULL,
                        content TEXT NOT NULL
                    )
                    """
                )
                cursor.execute(
                    "CREATE INDEX IF NOT EXISTS idx_session ON messages(session_id)"
                )
                cursor.execute(
                    "CREATE INDEX IF NOT EXISTS idx_session_panel ON messages(session_id, panel_id)"
                )
                cursor.execute(
                    """
                    CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_human_group
                    ON messages(session_id, type, panel_id, answer_group_id)
                    WHERE type = 'human' AND panel_id = '' AND answer_group_id <> ''
                    """
                )
                cursor.execute(
                    "CREATE INDEX IF NOT EXISTS idx_message_search_session ON message_search(session_id)"
                )
            conn.commit()

    def _active_workspace_id(self, cursor: Any) -> str:
        cursor.execute(
            """
            SELECT workspace_id
            FROM workspaces
            ORDER BY COALESCE(is_active, 0) DESC, updated_at DESC, created_at ASC
            LIMIT 1
            """
        )
        row = cursor.fetchone()
        return str(self._row_value(row, 0, "workspace_id") or DEFAULT_WORKSPACE_ID)

    def _ensure_session_exists(self) -> None:
        if not self.session_id:
            raise ValueError("session_id is required")
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    "SELECT session_id FROM sessions WHERE session_id = %s",
                    (self.session_id,),
                )
                if cursor.fetchone():
                    return
                now = time.time()
                cursor.execute(
                    """
                    INSERT INTO sessions (session_id, created_at, updated_at, title, workspace_id)
                    VALUES (%s, %s, %s, %s, %s)
                    """,
                    (self.session_id, now, now, "", self._active_workspace_id(cursor)),
                )
            conn.commit()

    def _resolve_default_panel_id(self, cursor: Any) -> str:
        cursor.execute(
            """
            SELECT panel_id
            FROM session_panels
            WHERE session_id = %s
            ORDER BY is_primary DESC, display_order ASC, updated_at ASC
            LIMIT 1
            """,
            (self.session_id,),
        )
        row = cursor.fetchone()
        return str(self._row_value(row, 0, "panel_id") or "").strip()

    def _load_message_rows(
        self,
        *,
        apply_context_limit: bool = True,
        panel_id: Optional[str] = None,
        exclude_ai_answer_group_id: Optional[str] = None,
    ) -> list[Any]:
        with self._connect() as conn:
            with conn.cursor() as cursor:
                effective_panel_id = (
                    str(panel_id or "").strip() or self._resolve_default_panel_id(cursor)
                )
                excluded_group_id = str(exclude_ai_answer_group_id or "").strip()
                params: list[Any] = [self.session_id]
                where = ["session_id = %s"]
                if effective_panel_id:
                    where.append("(COALESCE(panel_id, '') = '' OR COALESCE(panel_id, '') = %s)")
                    params.append(effective_panel_id)
                    if excluded_group_id:
                        where.append(
                            """
                            NOT (
                                type = 'ai'
                                AND COALESCE(panel_id, '') = %s
                                AND COALESCE(answer_group_id, '') = %s
                            )
                            """
                        )
                        params.extend([effective_panel_id, excluded_group_id])
                cursor.execute(
                    f"""
                    SELECT id, type, content, model_id, panel_id, answer_group_id,
                           images_json, files_json, sources_json, workflow_json,
                           task_id, task_type, COALESCE(feedback_value, 0), timestamp
                    FROM messages
                    WHERE {' AND '.join(where)}
                    ORDER BY id ASC
                    """,
                    tuple(params),
                )
                rows = cursor.fetchall()

        if apply_context_limit:
            context_limit = _env_int("CONTEXT_HISTORY_MESSAGES", 16)
            if context_limit > 0 and len(rows) > context_limit:
                rows = rows[-context_limit:]
        return rows

    def _load_messages(
        self,
        *,
        apply_context_limit: bool = True,
        panel_id: Optional[str] = None,
        exclude_ai_answer_group_id: Optional[str] = None,
    ) -> list[BaseMessage]:
        messages: list[BaseMessage] = []
        for row in self._load_message_rows(
            apply_context_limit=apply_context_limit,
            panel_id=panel_id,
            exclude_ai_answer_group_id=exclude_ai_answer_group_id,
        ):
            msg_type = str(self._row_value(row, 1, "type") or "")
            content = str(self._row_value(row, 2, "content") or "")
            images = _parse_json_list(self._row_value(row, 6, "images_json"))
            files = _parse_json_list(self._row_value(row, 7, "files_json"))
            if msg_type == "human":
                messages.append(
                    HumanMessage(
                        content=_build_human_message_content_for_model(
                            content,
                            images=images,
                            files=files,
                        )
                    )
                )
            elif msg_type == "ai":
                messages.append(AIMessage(content=content))
            elif msg_type == "system":
                messages.append(SystemMessage(content=content))
        return messages

    @property
    def messages(self) -> list[BaseMessage]:  # type: ignore[override]
        return self._load_messages(apply_context_limit=True)

    def get_panel_messages(self, panel_id: str) -> list[BaseMessage]:
        return self._load_messages(apply_context_limit=True, panel_id=panel_id)

    def get_panel_messages_for_rerun(
        self,
        panel_id: str,
        answer_group_id: str,
    ) -> list[BaseMessage]:
        return self._load_messages(
            apply_context_limit=True,
            panel_id=panel_id,
            exclude_ai_answer_group_id=answer_group_id,
        )

    def get_all_messages(self, panel_id: Optional[str] = None) -> list[BaseMessage]:
        return self._load_messages(apply_context_limit=False, panel_id=panel_id)

    def get_all_message_records(
        self,
        panel_id: Optional[str] = None,
    ) -> list[dict[str, Any]]:
        records: list[dict[str, Any]] = []
        for row in self._load_message_rows(apply_context_limit=False, panel_id=panel_id):
            records.append(
                {
                    "id": int(self._row_value(row, 0, "id") or 0),
                    "type": str(self._row_value(row, 1, "type") or ""),
                    "content": str(self._row_value(row, 2, "content") or ""),
                    "model_id": str(self._row_value(row, 3, "model_id") or ""),
                    "panel_id": str(self._row_value(row, 4, "panel_id") or ""),
                    "answer_group_id": str(self._row_value(row, 5, "answer_group_id") or ""),
                    "images": _normalize_images(
                        _parse_json_list(self._row_value(row, 6, "images_json"))
                    ),
                    "files": _normalize_files(
                        _parse_json_list(self._row_value(row, 7, "files_json"))
                    ),
                    "sources": _parse_json_list(self._row_value(row, 8, "sources_json")),
                    "workflow_nodes": _parse_json_list(
                        self._row_value(row, 9, "workflow_json")
                    ),
                    "task_id": str(self._row_value(row, 10, "task_id") or ""),
                    "task_type": str(self._row_value(row, 11, "task_type") or ""),
                    "feedback_value": _normalize_message_feedback_value(
                        self._row_value(row, 12, "feedback_value")
                    ),
                    "timestamp": float(self._row_value(row, 13, "timestamp") or 0),
                }
            )
        return records

    def add_message(
        self,
        message: BaseMessage,
        model_id: str = "",
        panel_id: str = "",
        answer_group_id: str = "",
        images: Optional[list[dict[str, Any]]] = None,
        files: Optional[list[dict[str, Any]]] = None,
        sources: Optional[list[dict[str, Any]]] = None,
        workflow_nodes: Optional[list[dict[str, Any]]] = None,
        task_id: str = "",
        task_type: str = "",
    ) -> None:
        if isinstance(message, HumanMessage):
            msg_type = "human"
        elif isinstance(message, AIMessage):
            msg_type = "ai"
        elif isinstance(message, SystemMessage):
            msg_type = "system"
        else:
            msg_type = "unknown"

        content_text = _normalize_content(message.content)
        normalized_images = _normalize_images(images)
        normalized_files = _normalize_files(files)
        normalized_sources = _normalize_metadata_list(sources)
        normalized_workflow = _normalize_metadata_list(workflow_nodes)
        now = time.time()

        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO messages (
                        session_id, type, content, timestamp, model_id, panel_id, answer_group_id,
                        images_json, files_json, sources_json, workflow_json, task_id, task_type
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (
                        self.session_id,
                        msg_type,
                        content_text,
                        now,
                        str(model_id or ""),
                        str(panel_id or ""),
                        str(answer_group_id or ""),
                        json.dumps(normalized_images, ensure_ascii=False),
                        json.dumps(normalized_files, ensure_ascii=False),
                        json.dumps(normalized_sources, ensure_ascii=False),
                        json.dumps(normalized_workflow, ensure_ascii=False),
                        str(task_id or ""),
                        str(task_type or ""),
                    ),
                )
                message_id = int(self._row_value(cursor.fetchone(), 0, "id") or 0)
                cursor.execute(
                    """
                    INSERT INTO message_search (rowid, session_id, content)
                    VALUES (%s, %s, %s)
                    ON CONFLICT(rowid) DO UPDATE SET
                        session_id = EXCLUDED.session_id,
                        content = EXCLUDED.content
                    """,
                    (message_id, self.session_id, content_text),
                )
                cursor.execute(
                    "SELECT title FROM sessions WHERE session_id = %s",
                    (self.session_id,),
                )
                current_title = str(self._row_value(cursor.fetchone(), 0, "title") or "")
                if not current_title and msg_type == "human":
                    title = _derive_session_title(
                        content_text,
                        images=normalized_images,
                        files=normalized_files,
                    )
                    if title:
                        cursor.execute(
                            "UPDATE sessions SET updated_at = %s, title = %s WHERE session_id = %s",
                            (now, title, self.session_id),
                        )
                    else:
                        cursor.execute(
                            "UPDATE sessions SET updated_at = %s WHERE session_id = %s",
                            (now, self.session_id),
                        )
                else:
                    cursor.execute(
                        "UPDATE sessions SET updated_at = %s WHERE session_id = %s",
                        (now, self.session_id),
                    )
            conn.commit()

    def add_user_message(
        self,
        message: str,
        model_id: str = "",
        panel_id: str = "",
        answer_group_id: str = "",
        images: Optional[list[dict[str, Any]]] = None,
        files: Optional[list[dict[str, Any]]] = None,
    ) -> None:
        self.add_message(
            HumanMessage(content=message),
            model_id=model_id,
            panel_id=panel_id,
            answer_group_id=answer_group_id,
            images=images,
            files=files,
        )

    def add_ai_message(
        self,
        message: str,
        model_id: str = "",
        panel_id: str = "",
        answer_group_id: str = "",
        images: Optional[list[dict[str, Any]]] = None,
        files: Optional[list[dict[str, Any]]] = None,
        sources: Optional[list[dict[str, Any]]] = None,
        workflow_nodes: Optional[list[dict[str, Any]]] = None,
        task_id: str = "",
        task_type: str = "",
    ) -> None:
        self.add_message(
            AIMessage(content=message),
            model_id=model_id,
            panel_id=panel_id,
            answer_group_id=answer_group_id,
            images=images,
            files=files,
            sources=sources,
            workflow_nodes=workflow_nodes,
            task_id=task_id,
            task_type=task_type,
        )

    def add_user_message_once(
        self,
        message: str,
        answer_group_id: str,
        images: Optional[list[dict[str, Any]]] = None,
        files: Optional[list[dict[str, Any]]] = None,
    ) -> None:
        if not answer_group_id:
            self.add_user_message(message, images=images, files=files)
            return

        content_text = _normalize_content(message)
        normalized_images = _normalize_images(images)
        normalized_files = _normalize_files(files)
        images_json = json.dumps(normalized_images, ensure_ascii=False)
        files_json = json.dumps(normalized_files, ensure_ascii=False)
        now = time.time()

        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT id
                    FROM messages
                    WHERE session_id = %s
                      AND type = 'human'
                      AND COALESCE(panel_id, '') = ''
                      AND COALESCE(answer_group_id, '') = %s
                    ORDER BY id ASC
                    LIMIT 1
                    """,
                    (self.session_id, answer_group_id),
                )
                existing_row = cursor.fetchone()
                if existing_row:
                    message_id = int(self._row_value(existing_row, 0, "id") or 0)
                    cursor.execute(
                        """
                        UPDATE messages
                        SET content = %s, images_json = %s, files_json = %s, timestamp = %s
                        WHERE id = %s
                        """,
                        (content_text, images_json, files_json, now, message_id),
                    )
                else:
                    cursor.execute(
                        """
                        INSERT INTO messages (
                            session_id, type, content, timestamp, model_id, panel_id, answer_group_id,
                            images_json, files_json
                        )
                        VALUES (%s, 'human', %s, %s, '', '', %s, %s, %s)
                        RETURNING id
                        """,
                        (
                            self.session_id,
                            content_text,
                            now,
                            answer_group_id,
                            images_json,
                            files_json,
                        ),
                    )
                    message_id = int(self._row_value(cursor.fetchone(), 0, "id") or 0)

                cursor.execute(
                    """
                    INSERT INTO message_search (rowid, session_id, content)
                    VALUES (%s, %s, %s)
                    ON CONFLICT(rowid) DO UPDATE SET
                        session_id = EXCLUDED.session_id,
                        content = EXCLUDED.content
                    """,
                    (message_id, self.session_id, content_text),
                )
                cursor.execute(
                    "SELECT title FROM sessions WHERE session_id = %s",
                    (self.session_id,),
                )
                current_title = str(self._row_value(cursor.fetchone(), 0, "title") or "")
                if not current_title:
                    title = _derive_session_title(
                        content_text,
                        images=normalized_images,
                        files=normalized_files,
                    )
                    if title:
                        cursor.execute(
                            "UPDATE sessions SET updated_at = %s, title = %s WHERE session_id = %s",
                            (now, title, self.session_id),
                        )
                    else:
                        cursor.execute(
                            "UPDATE sessions SET updated_at = %s WHERE session_id = %s",
                            (now, self.session_id),
                        )
                else:
                    cursor.execute(
                        "UPDATE sessions SET updated_at = %s WHERE session_id = %s",
                        (now, self.session_id),
                    )
            conn.commit()

    def delete_ai_messages_for_answer_group(
        self,
        panel_id: str,
        answer_group_id: str,
    ) -> None:
        if not panel_id or not answer_group_id:
            return
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    DELETE FROM messages
                    WHERE session_id = %s
                      AND type = 'ai'
                      AND COALESCE(panel_id, '') = %s
                      AND COALESCE(answer_group_id, '') = %s
                    RETURNING id
                    """,
                    (self.session_id, panel_id, answer_group_id),
                )
                deleted_ids = [
                    int(self._row_value(row, 0, "id") or 0)
                    for row in cursor.fetchall()
                ]
                if deleted_ids:
                    cursor.execute(
                        "DELETE FROM message_search WHERE rowid = ANY(%s)",
                        (deleted_ids,),
                    )
                    cursor.execute(
                        "UPDATE sessions SET updated_at = %s WHERE session_id = %s",
                        (time.time(), self.session_id),
                    )
            conn.commit()

    def set_message_feedback(
        self,
        *,
        feedback_value: int,
        message_id: Optional[int] = None,
        panel_id: str = "",
        answer_group_id: str = "",
    ) -> dict[str, Any] | None:
        normalized_feedback_value = _normalize_message_feedback_value(feedback_value)
        normalized_panel_id = str(panel_id or "").strip()
        normalized_answer_group_id = str(answer_group_id or "").strip()

        with self._connect() as conn:
            with conn.cursor() as cursor:
                target_row: Any | None = None
                if message_id is not None:
                    cursor.execute(
                        """
                        SELECT id, COALESCE(panel_id, ''), COALESCE(answer_group_id, '')
                        FROM messages
                        WHERE session_id = %s
                          AND id = %s
                          AND type = 'ai'
                        LIMIT 1
                        """,
                        (self.session_id, int(message_id)),
                    )
                    target_row = cursor.fetchone()
                else:
                    if not normalized_answer_group_id:
                        raise ValueError("Missing answer_group_id when message_id is not provided.")
                    cursor.execute(
                        """
                        SELECT id, COALESCE(panel_id, ''), COALESCE(answer_group_id, '')
                        FROM messages
                        WHERE session_id = %s
                          AND type = 'ai'
                          AND COALESCE(panel_id, '') = %s
                          AND COALESCE(answer_group_id, '') = %s
                        ORDER BY id DESC
                        LIMIT 1
                        """,
                        (
                            self.session_id,
                            normalized_panel_id,
                            normalized_answer_group_id,
                        ),
                    )
                    target_row = cursor.fetchone()

                if not target_row:
                    return None

                resolved_message_id = int(self._row_value(target_row, 0, "id") or 0)
                resolved_panel_id = str(self._row_value(target_row, 1, "panel_id") or "")
                resolved_answer_group_id = str(
                    self._row_value(target_row, 2, "answer_group_id") or ""
                )
                cursor.execute(
                    "UPDATE messages SET feedback_value = %s WHERE id = %s",
                    (normalized_feedback_value, resolved_message_id),
                )
                cursor.execute(
                    "UPDATE sessions SET updated_at = %s WHERE session_id = %s",
                    (time.time(), self.session_id),
                )
            conn.commit()

        return {
            "message_id": resolved_message_id,
            "panel_id": resolved_panel_id,
            "answer_group_id": resolved_answer_group_id,
            "feedback_value": normalized_feedback_value,
        }

    def clear(self) -> None:
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    "DELETE FROM message_search WHERE session_id = %s",
                    (self.session_id,),
                )
                cursor.execute(
                    "DELETE FROM messages WHERE session_id = %s",
                    (self.session_id,),
                )
                cursor.execute(
                    "UPDATE sessions SET updated_at = %s WHERE session_id = %s",
                    (time.time(), self.session_id),
                )
            conn.commit()

    def search_messages(self, query: str, *, limit: int = 20) -> list[dict[str, Any]]:
        normalized_query = str(query or "").strip().lower()
        if not normalized_query:
            return []
        safe_limit = max(1, min(100, int(limit or 20)))
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT m.id, m.type, m.content, m.timestamp
                    FROM message_search s
                    JOIN messages m ON m.id = s.rowid
                    WHERE s.session_id = %s
                      AND LOWER(COALESCE(s.content, '')) LIKE %s
                    ORDER BY m.id DESC
                    LIMIT %s
                    """,
                    (self.session_id, f"%{normalized_query}%", safe_limit),
                )
                rows = cursor.fetchall()
        return [
            {
                "id": int(self._row_value(row, 0, "id") or 0),
                "type": str(self._row_value(row, 1, "type") or ""),
                "content": str(self._row_value(row, 2, "content") or ""),
                "preview": _build_search_preview(
                    self._row_value(row, 2, "content"),
                    normalized_query,
                ),
                "timestamp": float(self._row_value(row, 3, "timestamp") or 0),
            }
            for row in rows
        ]
